modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL="https://github.com/0xCoDSnet/RoadArchitect/issues"
license = "${mod_license}"

[[mods]]
modId = "roadarchitect"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''
logoFile = "assets/roadarchitect/icon.png"
displayURL="https://github.com/0xCoDSnet/RoadArchitect"


[[dependencies.roadarchitect]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roadarchitect]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roadarchitect]]
modId = "cloth_config"
type = "required"
versionRange = "[${cloth_config_version},)"
ordering = "NONE"
side = "BOTH"

# Optional catalogue integration
[[dependencies.roadarchitect]]
modId = "catalogue"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[modproperties.roadarchitect]
catalogueImageIcon = "assets/roadarchitect/icon.png"

#[[dependencies.roadarchitect]]
#modId = "architectury"
#type = "required"
#versionRange = "[13.0.8,)"
#ordering = "AFTER"
#side = "BOTH"

[[mixins]]
config = "roadarchitect.mixins.json"
