modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "${mod_license}"

[[mods]]
modId = "roadarchitect"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''
#logoFile = ""

[[dependencies.roadarchitect]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.roadarchitect]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

#[[dependencies.roadarchitect]]
#modId = "architectury"
#type = "required"
#versionRange = "[13.0.8,)"
#ordering = "AFTER"
#side = "BOTH"

[[mixins]]
config = "roadarchitect.mixins.json"
