# Scan repository for secrets on push and pull requests
name: secret-scan
on:
  push:
  pull_request:

jobs:
  secret-scan:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: scan for secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true
